version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/indigo-heartbeat-service
hooks:
  AfterInstall:
   - location: scripts/build.sh
     timeout: 300
     runas: ec2-user
  ApplicationStart:
   - location: scripts/run.sh
     timeout: 300
     runas: ec2-user